- name: clean_services
  src: http://nexus-repository/repository/ansible-galaxy/releases/clean_services/clean_services-latest.tar.gz
- name: tools
  src: http://nexus-repository/repository/ansible-galaxy/releases/tools/tools-latest.tar.gz
- name: firewall
  src: http://nexus-repository/repository/ansible-galaxy/releases/firewall/firewall-latest.tar.gz
- name: ssh
  src: http://nexus-repository/repository/ansible-galaxy/releases/ssh/ssh-latest.tar.gz
- name: fail2ban
  src: http://nexus-repository/repository/ansible-galaxy/releases/fail2ban/fail2ban-latest.tar.gz
- name: portsentry
  src: http://nexus-repository/repository/ansible-galaxy/releases/portsentry/portsentry-latest.tar.gz
- name: ntp
  src: http://nexus-repository/repository/ansible-galaxy/releases/ntp/ntp-latest.tar.gz
- name: admin_tools
  src: http://nexus-repository/repository/ansible-galaxy/releases/admin_tools/admin_tools-latest.tar.gz
- name: docker
  src: http://nexus-repository/repository/ansible-galaxy/releases/docker/docker-latest.tar.gz
- name: monit
  src: http://nexus-repository/repository/ansible-galaxy/releases/monit/monit-latest.tar.gz
