---
front_name:
front_domain_name:
front_archive_file:
front_www_dir: "/var/www/{{ front_name }}"
root_group: root
nginx_sites_available_dir: /etc/nginx/sites-available
nginx_sites_enabled_dir: /etc/nginx/sites-enabled
nginx_user: "www-data"
